<a href="https://colab.research.google.com/github/keudithmanco-gif/Material-de-Analitica-de-Negocios-UDEA/blob/main/M3_S1_DatosFaltantesDuplicados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="banner" height="252px" width="1080px" src="https://docs.google.com/uc?export=download&id=18D9zTLyHjMFbwtI2Eenr0l5oGeH9a1Wq"  align="center" hspace="10px" vspace="0px" ></p>



# <font color='056938'> **Limpieza de datos** </font>
---

La limpieza de datos o *Data Cleansing* es la depuración de datos erróneos en una base de datos. Esta acción permite identificar datos incorrectos, incompletos o poco relevantes. Después de la limpieza, se sustituyen, modifican o eliminan por completo los datos inservibles.

# <font color='056938'> **¿Por qué es importante la limpieza de datos?** </font>
---

Los datos de calidad pueden variar dependiendo de cuál sea su cualidad, entre las principales se encuentran:

**Exactitud**: todos los datos deben ser precisos. Una forma de comprobar su exactitud es comparándolos con otras fuentes. Si esta fuente no existe o es inexacta, entonces la información que tienes también lo será.

**Coherencia**: la coherencia de los datos te permite saber si la información de contacto que tienes de una persona u organización es la misma en diferentes bases de datos, tablas o aplicaciones que utilices.

**Validez**: todos los datos deben cumplir con reglas o restricciones definidas. De igual forma, cada información puede ser validada para comprobar si es correcta o no.

**Uniformidad**: es importante que todos los datos dentro de tus bases tengan los mismos valores o unidades. Este es un elemento realmente indispensable a la hora de hacer data cleansing, pues de no tener todo en orden, el proceso se vuelve complejo.

# <font color='056938'> **¿Qué hacer en la limpieza de datos?** </font>
---

Existen varias técnicas de limpieza de datos que puede utilizar para mejorar la calidad de sus datos. Aquí se presentan algunas de las técnicas más comunes:

1.   Eliminar datos duplicados
2.   Imputar datos faltantes
3.   Corregir valores inconsistentes
4.   Estandarizar datos
5.   Eliminar valores atípicos
6.   Manejar errores
7.   Verificar la precisión de los datos

# <font color='056938'> **Datos duplicados** </font>
---

Los datos duplicados suelen presentarse por dos razones: la primera, por la entrada de datos inconsistente y la segunda, por los múltiples canales que capturan información de contacto.

## <font color='8EC044'> **¿Cómo se detectan los datos duplicados?** </font>

Usamos la función `duplicated()` de la libreria pandas para identificar datos duplicados. El método devuelve una Serie con valores `True` y `False` que indican qué filas en el DataFrame están duplicadas y cuáles no.

> <font color='46B8A9'> **Tip** </font> El tipo de resultado obtenido, Serie con valores `True` y `False`, es usualmente denomindado en Pandas como una máscara (o `mask` en inglés). Es decir, una estructura booleana que se utiliza para filtrar datos en un DataFrame o una Serie. Consiste en un conjunto de valores `True` o `False`, donde los valores `True` indican las filas o elementos que se deben conservar, y los `False` los que se deben descartar.

Considere el listado del registro de los usuarios que se han comunicado con la mesa de ayuda de la biblioteca de la Universidad de Antioquia durante un periodo de tiempo en particular

In [1]:
!gdown 1Or-DGN4av60uzzVJJNSb3he6yGH_6if5
import pandas as pd
import numpy as np

df_original = pd.read_csv('registros.csv')
df_original

Downloading...
From: https://drive.google.com/uc?id=1Or-DGN4av60uzzVJJNSb3he6yGH_6if5
To: /content/registros.csv
100% 586/586 [00:00<00:00, 1.71MB/s]

          timestamp        nombre                    correo  tiempo_activo
0  2024-09-16 12:35     Ana Arias     ana.araas@udea.edu.co              6
1  2024-09-15 04:44    Luis Perez    luis.perez@udea.edu.co             92
2  2024-09-14 12:06  Pedro arango  pedro.arango@udea.edu.co            112
3  2024-09-13 12:29  Sofia Correa  sofia.correa@udea.edu.co             34
4  2024-09-12 01:04   Carlos Rico   carlos.rico@udea.edu.co             42
5  2024-09-11 09:16     Ana Arias     ana.arias@udea.edu.co              6
6  2024-09-09 19:34    Juan Velez    juan.velez@udea.edu.co             68
7  2024-09-13 12:29  Sofia Correa  sofia.correa@udea.edu.co             34
8  2024-09-07 20:24    Pablo Maya    pablo.maya@udea.edu.co             25
9  2024-09-06 21:34    Luis Perez    luis.perez@udea.edu.co              3

Usamos la función `duplicated()` para identificar los registros repetidos.

In [ ]:
# Identificar filas duplicadas
duplicados1 = df_original.duplicated()

# Imprimir las filas duplicadas
duplicados1

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

Note que en nuestro caso identifica que el registro con el indice `7` es duplicado. En particular note que los registros con los indices `3` y `7` son idénticos

Es posible identificar duplicados con base en un subconjunto de las columnas

In [ ]:
# Identificar filas duplicadas de una columna específica (Autor)
duplicados2 = df_original.duplicated(subset=['nombre', 'correo'])

# Imprimir las filas duplicadas
duplicados2

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
dtype: bool

En este caso, considerando solo las columnas `nombre` y `correo`, las parejas de registros $(3, 7)$  y $(1, 9)$ estan repetidos. **¿Qué sucede con el par de registros $(0, 5)$?**

<font color='46B8A9'> **Parámetro `keep`** </font>

El parámetro `keep` de la función `duplicated()` en Pandas controla cuál o cuáles de las filas duplicadas se deben marcar como duplicadas. Tiene tres opciones posibles:

`keep`=`first` (por defecto): Marca como duplicadas todas las filas excepto la primera aparición de un duplicado.

`keep`=`last`: Marca como duplicadas todas las filas excepto la última aparición de un duplicado.

`keep`=`False`: Marca todas las filas duplicadas, sin excluir ninguna, es decir, tanto la primera como las siguientes apariciones serán marcadas como duplicadas.

### <font color='157699'> **Ejercicio** </font>
---

Use la función `duplicated()` para identificar los registros que se encuentran repetidos en función de solamente del `nombre` y el `correo`, tenga presente que deberá marcarse como repetidas todas las ocurrencias de un registro excepto aquella que tenga la fecha de aparición más temprana (debe conservarse el registro que tenga la fecha menor)

In [ ]:
# Escriba aquí su respuesta
df = df_original.copy()
df.sort_values(by='timestamp', ascending=True, inplace=True)
df.reset_index(drop=True,inplace=True)
df

          timestamp        nombre                    correo  tiempo_activo
0  2024-09-06 21:34    Luis Perez    luis.perez@udea.edu.co              3
1  2024-09-07 20:24    Pablo Maya    pablo.maya@udea.edu.co             25
2  2024-09-09 19:34    Juan Velez    juan.velez@udea.edu.co             68
3  2024-09-11 09:16     Ana Arias     ana.arias@udea.edu.co              6
4  2024-09-12 01:04   Carlos Rico   carlos.rico@udea.edu.co             42
5  2024-09-13 12:29  Sofia Correa  sofia.correa@udea.edu.co             34
6  2024-09-13 12:29  Sofia Correa  sofia.correa@udea.edu.co             34
7  2024-09-14 12:06  Pedro arango  pedro.arango@udea.edu.co            112
8  2024-09-15 04:44    Luis Perez    luis.perez@udea.edu.co             92
9  2024-09-16 12:35     Ana Arias     ana.araas@udea.edu.co              6

In [ ]:
mask = df.duplicated(subset=['nombre', "correo"])
mask

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8     True
9    False
dtype: bool

## <font color='8EC044'> **¿Qué hacer con los datos duplicados?** </font>

Usualmente los datos duplicados se remueven del dataframe. Para ello podemos hacerlo a través de la mascará que creamos anteriormente. Es decir:

In [ ]:
# Por defecto mantiene el primer registro y elimina las demás duplicados
dfsinduplicados1 = df_original[~mask]
dfsinduplicados1

          timestamp      nombre                  correo  tiempo_activo
6  2024-09-09 19:34  Juan Velez  juan.velez@udea.edu.co             68
8  2024-09-07 20:24  Pablo Maya  pablo.maya@udea.edu.co             25

Alternativamente, podemos usuar la función `drop_duplicates()` que también puede considerar parámetro `keep` que discutimos anteriormente.

In [ ]:
# Por defecto mantiene el primer registro y elimina las demás duplicados
dfsinduplicados1 = df.drop_duplicates(subset=['nombre', 'correo'])
dfsinduplicados1

          timestamp        nombre                    correo  tiempo_activo
0  2024-09-06 21:34    Luis Perez    luis.perez@udea.edu.co              3
1  2024-09-07 20:24    Pablo Maya    pablo.maya@udea.edu.co             25
2  2024-09-09 19:34    Juan Velez    juan.velez@udea.edu.co             68
3  2024-09-11 09:16     Ana Arias     ana.arias@udea.edu.co              6
4  2024-09-12 01:04   Carlos Rico   carlos.rico@udea.edu.co             42
5  2024-09-13 12:29  Sofia Correa  sofia.correa@udea.edu.co             34
7  2024-09-14 12:06  Pedro arango  pedro.arango@udea.edu.co            112
9  2024-09-16 12:35     Ana Arias     ana.araas@udea.edu.co              6

# <font color='056938'> **Datos similares** </font>

En algunos casos estamos interesados en identificar registros que son bastante similares pero no identicos. Este tipo de registros son usualmente debidos a errores en la entrada de los datos.

En nuestra base de datos los registros con indices `3` y `9`

In [ ]:
df.iloc[[3,9]]

          timestamp     nombre                 correo  tiempo_activo
3  2024-09-11 09:16  Ana Arias  ana.arias@udea.edu.co              6
9  2024-09-16 12:35  Ana Arias  ana.araas@udea.edu.co              6

Existen formas de identificar dichos registros usando librerias como `fuzzywuzzy`.

`fuzzywuzzy` es un paquete de Python utilizado para comparar cadenas de texto y realizar coincidencias difusas (fuzzy matching), lo que resulta útil cuando necesitas comparar dos cadenas que no son exactamente iguales, pero son similares. Se basa en la distancia de Levenshtein para calcular las diferencias entre secuencias de caracteres

Note por ejemplo, que podemos calcular el nivel de similaridad entre estos dos registros:

In [ ]:
!pip install fuzzywuzzy
!pip install python-Levenshtein

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0
Collecting python-Levenshtein
  Downloading python_levenshtein-0.27.5-py3-none-any.whl.metadata (3.9 kB)
Collecting Levenshtein==0.27.5 (from python-Levenshtein)
  Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.5->python-Levenshtein)
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading python_levenshtein-0.27.5-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (157 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.4/157.4 kB 5.7 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 77.0 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.27.5 python-Levenshtein-0.27.5 rapidfuzz-3.14.6

In [ ]:
from fuzzywuzzy import fuzz

# Comparación simple"Hola Mundo"
puntuacion = fuzz.ratio(df.iloc[3]['correo'], df.iloc[9]['correo'])
puntuacion

95

### <font color='157699'> **Ejercicio** </font>

Cree una máscara que identifique los registros que tienen un grado de similaridad con una puntuación de más de 90.

In [ ]:
import pandas as pd
from fuzzywuzzy import fuzz

# Similarity threshold
threshold = 90

# Create a mask to track duplicate rows
mask = pd.Series([True] * len(df))


# Compare each row with every other row, marking duplicates
for i in range(len(df)):
    if mask[i]:  # Only proceed if the row is still considered unique
        for j in range(i+1, len(df)):
            similarity = fuzz.ratio(df.loc[i, 'nombre'], df.loc[j, 'nombre'])
            if similarity > threshold:
                mask[j] = False  # Mark similar rows as False


mask

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7     True
8    False
9    False
dtype: bool

# <font color='056938'> **Datos faltantes** </font>



Los **valores faltantes** son puntos de datos que están ausentes para una variable específica en un conjunto de datos. Pueden estar representados de varias formas, como celdas en blanco, valores nulos, `null`,  o símbolos especiales como `NA` o `None`. Estos puntos de datos faltantes suponen un desafío importante en el análisis de datos y pueden llevar a resultados inexactos o sesgados.

Hay muchos tipos de datos faltantes y muchas razones por las cuales pueden ocurrir. Estos dos factores son decisivos al enfrentar la ausencia de datos en el momento de analizar los resultados, donde lo principal es decidir si la pérdida es aleatoria, es decir, afecta por igual a todos los individuos, o bien puede ser debida a una razón o razones específicas que pueden introducir sesgos que invaliden los resultados.

## <font color='8EC044'> **Tipos de datos faltantes** </font>

Una forma útil de clasificar los datos faltantes es de acuerdo a la forma como estos se presentan en los datos. Es decir, si la pérdida es aleatoria y afecta por igual a todos los individuos,

### <font color='157699'> **Datos Faltantes Completamente al Azar (`MCAR`)** </font>
La probabilidad de que un valor esté faltante no depende ni de las variables observadas ni de los valores faltantes mismos. Es como si los datos faltantes fueran seleccionados al azar.
* **Ejemplo:** Imagina una encuesta donde algunas preguntas no son respondidas debido a un error en la impresión de la encuesta. La probabilidad de que una pregunta específica esté sin responder no depende de ninguna otra pregunta ni de la respuesta a esa pregunta.


### <font color='157699'> **Datos Faltantes al Azar (`MAR`)** </font>

La probabilidad de que un valor esté faltante depende de otras variables observadas en el conjunto de datos, pero no del valor faltante en sí.
* **Ejemplo:** En una encuesta sobre hábitos de ejercicio, es más probable que las personas mayores no reporten su peso. La probabilidad de que el peso esté faltante depende de la edad (una variable observada), pero no del peso real de la persona.

### <font color='157699'> **Datos Faltantes No al Azar (`MNAR`)** </font>

La probabilidad de que un valor esté faltante depende del valor faltante mismo o de otras variables no observadas. Es el tipo de datos faltantes más difícil de manejar.
* **Ejemplo:** En un estudio sobre depresión, las personas con depresión severa pueden ser menos propensas a responder preguntas sobre su estado de ánimo. La probabilidad de que una respuesta sobre el estado de ánimo esté faltante depende del estado de ánimo real de la persona (un valor faltante).

  Las personas con mayores ingresos pueden negarse a compartir la información exacta en una encuesta o cuestionario que pregunte sobre ingresos.



La identificación del tipo de datos faltantes es crucial porque determina el método adecuado para tratarlos. Los datos `MCAR` y `MAR` pueden ser manejados con técnicas más simples como la eliminación de casos con datos faltantes o la imputación de valores faltantes. Sin embargo, los datos `MNAR` requieren métodos más complejos y específicos.

### <font color='157699'> **Ejercicio** </font>

Considere el siguiente dataframe en el que se han considerado los registros de varios mimebros del personal administrativo de la universidad, considerando tres variables adicionales:


* `genero`
* `experiencia`: años de experiencia
* `ingreso`: Ingresos mensuales
* `ansiedad`: si ha experimentado ansiedad en el último mes

In [ ]:
import pandas as pd
!gdown 1-JfcYV-ErOImuAmStW2fTDEzNTesCg80
df_original = pd.read_csv('registros_v2.csv')
df = df_original.copy()
df

Downloading...
From: https://drive.google.com/uc?id=1-JfcYV-ErOImuAmStW2fTDEzNTesCg80
To: /content/registros_v2.csv
100% 1.31k/1.31k [00:00<00:00, 3.01MB/s]

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,3.0,M,2,1695116.0,no
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,NaN,M,1,1561624.0,no
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,NaN
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,NaN,F,9,2217454.0,no
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,42.0,M,2,1678013.0,no
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,34.0,F,2,1641407.0,si
6,2024-09-14 12:06,Pedro Arango,pedro.arango@udea.edu.co,112.0,M,3,1376695.0,no
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,20.0,F,1,NaN,no
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,35.0,M,3,1745424.0,no
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,50.0,F,3,1354074.0,no
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,12.0,M,3,1518317.0,no
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,28.0,F,8,NaN,no
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,NaN,M,4,1712200.0,NaN
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,60.0,F,7,2039432.0,no
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,22.0,M,7,2103873.0,no
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,NaN,F,6,1964195.0,no
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN

Discuta para los datos faltantes cuál tipo considera usted que podrían considerarse

## <font color='8EC044'> **¿Cómo se detectan los datos faltantes?** </font>

Anteriormente ya habiamos discutido la función `info()` de pandas que nos entrega información sobre los datos no nulos para cada una de las variables

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      17 non-null     object
 1   nombre         17 non-null     object
 2   correo         17 non-null     object
 3   tiempo_activo  13 non-null     float64
 4   genero         17 non-null     object
 5   Experiencia    17 non-null     int64
 6   ingreso        15 non-null     float64
 7   ansiedad       14 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.2+ KB

Las funciones `isnull()` y `notnull()` de la libreria `pandas` nos indican cuando un valor es nulo o no, respectivamente.

Podemos usarlo para obtener el número de registros nulos por cada columna

In [ ]:
df.isnull().sum()

timestamp        0
nombre           0
correo           0
tiempo_activo    4
genero           0
Experiencia      0
ingreso          2
ansiedad         3
dtype: int64

Esta misma función puede usarse para filtrar aquellos registros que tienen variables nulos en el dataframe, por ejemplo

In [ ]:
rows_with_nulls = df[df.isnull().any(axis=1)]
rows_with_nulls

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,NaN,M,1,1561624.0,no
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,NaN
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,NaN,F,9,2217454.0,no
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,20.0,F,1,NaN,no
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,28.0,F,8,NaN,no
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,NaN,M,4,1712200.0,NaN
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,NaN,F,6,1964195.0,no
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN

Tambien puede usarse para  obtener los registros con valores nulos en alguna columna en particular

In [ ]:
mask = pd.isnull(df['ansiedad'])
df[mask]

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,NaN
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,NaN,M,4,1712200.0,NaN
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN

### <font color='157699'> **Ejercicio** </font>

Identifique las columnas que tienen por lo menos un dato faltante

In [ ]:
# Escriba aqui su respuesta
columns_with_nulls = df.columns[df.isnull().any()]

print("Columns with null values:")
columns_with_nulls

Columns with null values:

Index(['tiempo_activo', 'ingreso', 'ansiedad'], dtype='object')

## <font color='8EC044'> **Estrategias para el tratamiento de datos faltantes** </font>

Existen diversas estrategias para gestionar los datos faltantes en una base de datos. Estas podrian clasificarse en dos tipos:


*   **Eliminar entradas**: se refiere al proceso de eliminar variables (columnas) o registros (filas) para los cuales existen valores faltantes.  
*   **Imputar valores**: se refiere al proceso de reemplazar los valores faltantes en un conjunto de datos por estimaciones o valores plausibles

El uso de una estrategia u otra dependerá del tipo de  datos faltantes, pero a su veces generará consecuencias diferentes en los análisis y resultados

### <font color='157699'> **Eliminar entradas** </font>

En esta alternativa se opta por filtrar, no incluir en el análisis,variables o registros para los que existen datos faltantes.

Esta aproximación tiene como consecuencia una perdida de información. Que, dado el caso en el que los datos faltantes sean númerosos, podria ser considerable.

Puede optarse por:
* Eliminar  las variables (columnas) para las que existen datos faltantes.  Esto es apropiado cuando los datos faltantes se concentran en unas pocas columnas y para cada una de ellas el número de faltantes es significativo
* Eliminar los registros que tienen datos faltantes.

Este tipo de estrategias se ajusta a mejor a datos faltantes del tipo `MCAR` o `MAR`, siempre que  la pérdida de información asociada no impacte significativamente el análisis

Para eliminar las columnas o filas que tienes datos faltantes usamos el método `dropna()`. Note que por defecto, se eliminan los registros que tienen algun dato faltante.

In [ ]:
df.dropna()

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,3.0,M,2,1695116.0,no
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,42.0,M,2,1678013.0,no
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,34.0,F,2,1641407.0,si
6,2024-09-14 12:06,Pedro Arango,pedro.arango@udea.edu.co,112.0,M,3,1376695.0,no
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,35.0,M,3,1745424.0,no
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,50.0,F,3,1354074.0,no
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,12.0,M,3,1518317.0,no
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,60.0,F,7,2039432.0,no
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,22.0,M,7,2103873.0,no

Para eliminar las columnas que tienen datos faltantes se usa el argumento `df.dropna(axis=1)`

In [ ]:
df.dropna(axis=1)

,timestamp,nombre,correo,genero,Experiencia
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,M,2
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,M,1
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,M,3
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,F,9
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,M,2
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,F,2
6,2024-09-14 12:06,Pedro Arango,pedro.arango@udea.edu.co,M,3
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,F,1
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,M,3
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,F,3
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,M,3
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,F,8
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,M,4
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,F,7
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,M,7
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,F,6
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,M,2

Adicionalmente, hay otros parametros para controlar que filas o columnas eliminar, algunos de ellos son:

| Argumento  | Descripción                                                                                                     | Valores posibles                                  | Valor predeterminado |
|------------|-----------------------------------------------------------------------------------------------------------------|---------------------------------------------------|----------------------|
| `axis`     | Determina si se eliminan filas o columnas con valores faltantes.                                                 | `0`: filas, `1`: columnas | `0`                  |
| `how`      | Especifica si se eliminan filas/columnas si **algún** o **todos** los valores están faltantes.                    | `'any'`: si alguno, `'all'`: si todos              | `'any'`              |
| `thresh`   | Requiere un número mínimo de valores no faltantes para evitar eliminar la fila o columna.                        | Número entero                                      | `None`               |
| `subset`   | Lista de filas o columnas específicas para considerar al verificar valores faltantes.                            | Lista de nombres de columnas/índices               | `None`               |
| `inplace`  | Si se establece en `True`, modifica el DataFrame original sin devolver una copia.                                | `True` o `False`                                   | `False`              |

#### <font color='46B8A9'> **Ejercicio** </font>

Considere la siguiente instrucción, interprete que entradas se eliminan

In [ ]:
df.dropna(axis=0, thresh=7)

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,3.0,M,2,1695116.0,no
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,NaN,M,1,1561624.0,no
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,NaN
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,NaN,F,9,2217454.0,no
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,42.0,M,2,1678013.0,no
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,34.0,F,2,1641407.0,si
6,2024-09-14 12:06,Pedro Arango,pedro.arango@udea.edu.co,112.0,M,3,1376695.0,no
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,20.0,F,1,NaN,no
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,35.0,M,3,1745424.0,no
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,50.0,F,3,1354074.0,no
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,12.0,M,3,1518317.0,no
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,28.0,F,8,NaN,no
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,60.0,F,7,2039432.0,no
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,22.0,M,7,2103873.0,no
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,NaN,F,6,1964195.0,no
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN

### <font color='157699'> **Imputar datos** </font>

Al imputar valores a los datos faltantes, es importante, entre otros aspcctos, identificar que tipo de variable es aquella para la que se quiere imputar el dato, el número de datos faltantes en dicha variable

#### <font color='46B8A9'> **Imputar con un estadístico de tendencia** </font>

Las columnas en el conjunto de datos que tienen valores numéricos continuos pueden ser reemplazadas con la media, mediana o moda de los valores restantes en la columna.

La imputación con media y mediana puede proporcionar una buena estimación de los valores faltantes, respectivamente, para datos distribuidos normalmente y datos sesgados. Este enfoque es popularmente utilizado cuando hay un pequeño número de valores faltantes en los datos. Sin embargo, cuando hay muchos valores faltantes, los resultados de la media o la mediana pueden ocasionar una pérdida de variación en los datos. Así mismo, la imputación con la media es sensible a los valores atípicos.

Para imputar un valor a un dato faltante usamos la función `fillna()`. Note por ejemplo como podemos imputar un valor para los datos faltantes en la columna `tiempo_activo`. Note que hemos obviado la instrucción `inplace = True` para evitar cambiar el dataframe original y así poder usarlo en los siguientes ejemplos

In [ ]:
df['tiempo_activo'].fillna(df['tiempo_activo'].mean())

0       3.000000
1      40.461538
2      68.000000
3      40.461538
4      42.000000
5      34.000000
6     112.000000
7      20.000000
8      35.000000
9      50.000000
10     12.000000
11     28.000000
12     40.461538
13     60.000000
14     22.000000
15     40.461538
16     40.000000
Name: tiempo_activo, dtype: float64

En algunas ocasiones, podriamos saber que los valores de las variables para las que hay datos faltantes, tienen comportamientos distintos para grupos diferentes en la base de datos. En esto casos es recomendable hacer la imputación teniendo en cuenta estos grupos. Para ello, usamos el método de `groupby()` que habiamos discutido anteriormente.

In [ ]:
df['tiempo_activo'].fillna(df.groupby('genero')['tiempo_activo'].transform('mean'))

0       3.00
1      41.75
2      68.00
3      38.40
4      42.00
5      34.00
6     112.00
7      20.00
8      35.00
9      50.00
10     12.00
11     28.00
12     41.75
13     60.00
14     22.00
15     38.40
16     40.00
Name: tiempo_activo, dtype: float64

#### <font color='46B8A9'> **Imputar con un estadístico de frecuencia** </font>

Cuando los valores faltantes provienen de columnas categóricas (de tipo cadena o numéricas), los valores faltantes pueden ser reemplazados con la categoría más frecuente. Si el número de valores faltantes es muy grande, entonces se pueden reemplazar con una nueva categoría.

Veamos el número de valores faltantes en la variable `ansiedad`

In [ ]:
df['ansiedad'].value_counts(dropna=False)

ansiedad
no     13
NaN     3
si      1
Name: count, dtype: int64



---
**En cuál de los tipos de datos faltantes clasificaría aquellos pertenecientes a la variable `ansiedad`?**


---

Dado que la gran mayoria de los datos tienen categoria `no`, una aproximación conservadora sería imputar los datos faltantes con este valor

In [ ]:
df['ansiedad'].fillna('no')

0     no
1     no
2     no
3     no
4     no
5     si
6     no
7     no
8     no
9     no
10    no
11    no
12    no
13    no
14    no
15    no
16    no
Name: ansiedad, dtype: object

Cuando el número de valores faltantes son muchos, podríamos imputar un valor de referencia que nos permita interpretar en el análisis que dichos valores eran datos faltantes

In [ ]:
df['ansiedad'].fillna('99')

0     no
1     no
2     99
3     no
4     no
5     si
6     no
7     no
8     no
9     no
10    no
11    no
12    99
13    no
14    no
15    no
16    99
Name: ansiedad, dtype: object

#### <font color='46B8A9'> **Imputar con valores adyacentes** </font>

El relleno hacia adelante (`ffill`) y el relleno hacia atrás (`bfill`) son métodos utilizados para llenar valores faltantes llevando hacia adelante el último valor observado que no está faltante (para `ffill`) o llevando hacia atrás el siguiente valor observado que no está faltante (para `bfill`). Estos métodos son especialmente útiles para datos de series temporales.

In [ ]:
import numpy as np

df.sort_values(by='timestamp', ascending=True, inplace=True)
df.reset_index(drop=True,inplace=True)
df.loc[6, 'timestamp'] = np.nan
df

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,3.0,M,2,1695116.0,no
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,NaN,M,1,1561624.0,no
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,NaN
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,NaN,F,9,2217454.0,no
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,42.0,M,2,1678013.0,no
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,34.0,F,2,1641407.0,si
6,NaN,Pedro Arango,pedro.arango@udea.edu.co,112.0,M,3,1376695.0,no
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,20.0,F,1,NaN,no
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,35.0,M,3,1745424.0,no
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,50.0,F,3,1354074.0,no
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,12.0,M,3,1518317.0,no
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,28.0,F,8,NaN,no
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,NaN,M,4,1712200.0,NaN
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,60.0,F,7,2039432.0,no
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,22.0,M,7,2103873.0,no
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,NaN,F,6,1964195.0,no
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN

In [ ]:
df['timestamp'].fillna(method='ffill')

/tmp/ipykernel_14547/3773200586.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['timestamp'].fillna(method='ffill')

0     2024-09-06 21:34
1     2024-09-07 20:24
2     2024-09-09 19:34
3     2024-09-11 09:16
4     2024-09-12 01:04
5     2024-09-13 12:29
6     2024-09-13 12:29
7     2024-09-15 08:45
8     2024-09-16 14:32
9     2024-09-17 17:55
10    2024-09-18 10:23
11    2024-09-19 13:37
12    2024-09-20 09:15
13    2024-09-21 18:48
14    2024-09-22 11:12
15    2024-09-23 15:04
16    2024-09-24 07:29
Name: timestamp, dtype: object

De igual forma, podriamos aplicarlo para todas las columnas del dataframe o un subconjunto de estas:

In [ ]:
df.bfill()

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,3.0,M,2,1695116.0,no
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,68.0,M,1,1561624.0,no
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,no
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,42.0,F,9,2217454.0,no
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,42.0,M,2,1678013.0,no
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,34.0,F,2,1641407.0,si
6,2024-09-15 08:45,Pedro Arango,pedro.arango@udea.edu.co,112.0,M,3,1376695.0,no
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,20.0,F,1,1745424.0,no
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,35.0,M,3,1745424.0,no
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,50.0,F,3,1354074.0,no
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,12.0,M,3,1518317.0,no
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,28.0,F,8,1712200.0,no
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,60.0,M,4,1712200.0,no
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,60.0,F,7,2039432.0,no
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,22.0,M,7,2103873.0,no
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,40.0,F,6,1964195.0,no
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN


#### <font color='46B8A9'> **Imputación basada en modelo (Regresion)** </font>

Para la imputación es posible utilizar la correlación entre la variable que contiene el valor faltante y otras variables.

En este método, se utilizan modelos predictivos para imputar valores faltantes basándose en otras características del conjunto de datos.

El modelo de regresión o clasificación se puede usar para la predicción de valores faltantes, dependiendo de la naturaleza (categórica o continua) de la característica que tiene el valor faltante.

Note que en este caso deberemos usar modelos que de momento no se han cubierto en el curso, pero para los cuales ilustraremos su forma de uso:

In [ ]:
from sklearn.linear_model import LinearRegression

# Seleccionamos las columnas de interes
df_filtered = df[['tiempo_activo',	'genero',	'Experiencia', 'ingreso']]
# filtramos los datos eliminando los nulos excepto para la columna ingreso
df_filtered = df_filtered.dropna(subset=['tiempo_activo', 'genero'])
# recodificamos la columna genero con 0 y 1
df_filtered = pd.get_dummies(df_filtered, columns=['genero'], drop_first=True)

# Partimos los datos entre los que tienen el ingreso como faltane y los que no
test_data = df_filtered[df_filtered["ingreso"].isnull()==True]
traindf = df_filtered[df_filtered["ingreso"].isnull()==False]

y_train = traindf["ingreso"]
X_train = traindf.drop("ingreso", axis=1)
X_test = test_data.drop("ingreso", axis=1)

# Llevamos a cabo la regresion
model = LinearRegression()
model.fit(X_train, y_train)

# Obtenemos pa predicción
y_pred = model.predict(X_test)

test_data['ingreso'] = y_pred
test_data['ingreso']

/tmp/ipykernel_14547/1477844267.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data['ingreso'] = y_pred

7     1.450540e+06
11    2.133355e+06
Name: ingreso, dtype: float64

#### <font color='46B8A9'> **Interpolar** </font>

La interpolación es una técnica utilizada para llenar valores faltantes basándose en los valores de los puntos de datos adyacentes. Esta técnica se usa principalmente en datos de series temporales o en situaciones donde se espera que los puntos de datos faltantes varíen de manera suave o sigan una cierta tendencia. También se utiliza en casos de datos muestreados de manera regular.

La interpolación puede entenderse como un promedio ponderado. Los pesos están relacionados inversamente con la distancia a los puntos vecinos.

In [ ]:
# Linear interpolation for a specific column
df['tiempo_activo'].interpolate(method='linear')

0       3.0
1      35.5
2      68.0
3      55.0
4      42.0
5      34.0
6     112.0
7      20.0
8      35.0
9      50.0
10     12.0
11     28.0
12     44.0
13     60.0
14     22.0
15     31.0
16     40.0
Name: tiempo_activo, dtype: float64

Similarmente puede hacerse para todas las columnas numericas del dataFrame

In [ ]:
# Linear interpolation for the entire DataFrame
df.interpolate(method='linear')

/tmp/ipykernel_14547/617235804.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear')

,timestamp,nombre,correo,tiempo_activo,genero,Experiencia,ingreso,ansiedad
0,2024-09-06 21:34,Luis Perez,luis.perez@udea.edu.co,3.0,M,2,1695116.0,no
1,2024-09-07 20:24,Pablo Maya,pablo.maya@udea.edu.co,35.5,M,1,1561624.0,no
2,2024-09-09 19:34,Juan Velez,juan.velez@udea.edu.co,68.0,M,3,1705874.0,NaN
3,2024-09-11 09:16,Ana Arias,ana.arias@udea.edu.co,55.0,F,9,2217454.0,no
4,2024-09-12 01:04,Carlos Rico,carlos.rico@udea.edu.co,42.0,M,2,1678013.0,no
5,2024-09-13 12:29,Sofia Correa,sofia.correa@udea.edu.co,34.0,F,2,1641407.0,si
6,NaN,Pedro Arango,pedro.arango@udea.edu.co,112.0,M,3,1376695.0,no
7,2024-09-15 08:45,Laura Salazar,laura.salazar@udea.edu.co,20.0,F,1,1561059.5,no
8,2024-09-16 14:32,Mario Gomez,mario.gomez@udea.edu.co,35.0,M,3,1745424.0,no
9,2024-09-17 17:55,Elena Vargas,elena.vargas@udea.edu.co,50.0,F,3,1354074.0,no
10,2024-09-18 10:23,Roberto Castillo,roberto.castillo@udea.edu.co,12.0,M,3,1518317.0,no
11,2024-09-19 13:37,Valeria Medina,valeria.medina@udea.edu.co,28.0,F,8,1615258.5,no
12,2024-09-20 09:15,Jorge Ruiz,jorge.ruiz@udea.edu.co,44.0,M,4,1712200.0,NaN
13,2024-09-21 18:48,Natalia Morales,natalia.morales@udea.edu.co,60.0,F,7,2039432.0,no
14,2024-09-22 11:12,Andr s Torres,andres.torres@udea.edu.co,22.0,M,7,2103873.0,no
15,2024-09-23 15:04,Catalina Silva,catalina.silva@udea.edu.co,31.0,F,6,1964195.0,no
16,2024-09-24 07:29,Alejandro Soto,alejandro.soto@udea.edu.co,40.0,M,2,1601115.0,NaN

#### <font color='46B8A9'> **`k` vecino más cercanos** </font>

Una estrategia similar, imputa un valor para el dato faltante  en función de los valores de sus vecinos más cercanos en el espacio de características (`features`). Una de las técnicas más empleadas en este contexto es k-Vecinos Más Cercanos (`KNN`)

La idea es encontrar los k puntos de datos más cercanos y utilizar sus valores para imputar los valores faltantes.

Considere por ejemplo el caso en el que queremos imputar los datos faltantes en `ingeso`,  `tiempo_activo` y `Experiencia`con base en la registros con caracteristicas similares

In [ ]:
data = df[['ingreso', 'tiempo_activo', 'Experiencia']]
data

      ingreso  tiempo_activo  Experiencia
0   1695116.0            3.0            2
1   1561624.0            NaN            1
2   1705874.0           68.0            3
3   2217454.0            NaN            9
4   1678013.0           42.0            2
5   1641407.0           34.0            2
6   1376695.0          112.0            3
7         NaN           20.0            1
8   1745424.0           35.0            3
9   1354074.0           50.0            3
10  1518317.0           12.0            3
11        NaN           28.0            8
12  1712200.0            NaN            4
13  2039432.0           60.0            7
14  2103873.0           22.0            7
15  1964195.0            NaN            6
16  1601115.0           40.0            2

In [ ]:
from sklearn.impute import KNNImputer
import pandas as pd

# Create a KNN imputer
imputer = KNNImputer(n_neighbors=3)

# Perform imputation
data_imputed = imputer.fit_transform(data)
imputed_df = pd.DataFrame(data_imputed, columns=data.columns)
imputed_df

         ingreso  tiempo_activo  Experiencia
0   1.695116e+06       3.000000          2.0
1   1.561624e+06      29.333333          1.0
2   1.705874e+06      68.000000          3.0
3   2.217454e+06      23.333333          9.0
4   1.678013e+06      42.000000          2.0
5   1.641407e+06      34.000000          2.0
6   1.376695e+06     112.000000          3.0
7   1.792566e+06      20.000000          1.0
8   1.745424e+06      35.000000          3.0
9   1.354074e+06      50.000000          3.0
10  1.518317e+06      12.000000          3.0
11  1.964616e+06      28.000000          8.0
12  1.712200e+06      38.666667          4.0
13  2.039432e+06      60.000000          7.0
14  2.103873e+06      22.000000          7.0
15  1.964195e+06      36.000000          6.0
16  1.601115e+06      40.000000          2.0

# <font color='056938'> **Reto** </font>

Considere el siguiente DataFrame que contiene la información del estado de las estaciones en el sistema EcoBici durante las 24 horas de un perido de 5 días.

In [ ]:
import pandas as pd

!gdown 1IV1uYrn1hP-dnYoEaRFXX55bXWxGPUEt
df = pd.read_csv("stations_status_faltantes.csv")
df.head()

Downloading...
From: https://drive.google.com/uc?id=1IV1uYrn1hP-dnYoEaRFXX55bXWxGPUEt
To: /content/stations_status_faltantes.csv
100% 32.7M/32.7M [00:00<00:00, 52.7MB/s]

/tmp/ipykernel_14547/3000785547.py:4: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("stations_status_faltantes.csv")

,station_id,short_name,name,lat,lon,capacity,num_bikes_available,num_bikes_disabled,num_docks_available,num_docks_disabled,is_installed,is_renting,is_returning,last_reported,eightd_has_available_keys,is_charging,timestamp
0,1,710,CE-710 Molino del Rey - Glorieta de la Lealtad,19.416795,-99.192508,39,14.0,0.0,25.0,0.0,1.0,1.0,1.0,1.758892e+09,False,False,26/09/2025 08:15
1,5,407,CE-407 Prolongación Xochicalco-General Emilia...,19.367266,-99.158656,19,1.0,1.0,17.0,0.0,1.0,1.0,1.0,1.758892e+09,False,False,26/09/2025 08:15
2,6,428,CE-428 Prolongación Uxmal-Av. Popocatépetl (E...,19.363404,-99.160395,27,11.0,3.0,13.0,0.0,1.0,1.0,1.0,1.758892e+09,False,False,26/09/2025 08:15
3,7,427,CE-427 Avenida México-Coyoacán-Av. Popocatépet...,19.364906,-99.162987,19,2.0,6.0,11.0,0.0,1.0,1.0,1.0,1.758892e+09,False,False,26/09/2025 08:15
4,8,443,CE-443 Bruno Traven-Golondrinas,19.359583,-99.162085,31,7.0,0.0,24.0,0.0,1.0,1.0,1.0,1.758892e+09,False,False,26/09/2025 08:15

Identifique y gestiones los datos duplicados y faltanes. Para ello use la siguiente [plantilla](https://drive.google.com/file/d/1CsoD8H2fp86qfSfFXxCrmLjHrUubKbQK/view?usp=sharing):