<a href="https://colab.research.google.com/github/keudithmanco-gif/Material-de-Analitica-de-Negocios-UDEA/blob/main/M3_S3_Outliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="banner" height="252px" width="1080px" src="https://docs.google.com/uc?export=download&id=18D9zTLyHjMFbwtI2Eenr0l5oGeH9a1Wq"  align="center" hspace="10px" vspace="0px" ></p>

# <font color='056938'> **Introducción** </font>
Los outliers (valores atípicos) son observaciones o puntos de datos que se alejan significativamente de otros en un conjunto de datos.

## <font color='8EC044'> **Causas de los datos atípicos** </font>

Los *outliers* pueden ser causados por una variedad de factores, y a menudo resultan de la variabilidad genuina en los datos o de errores en la recopilación, medición o registro de los mismos. Algunas causas comunes de *outliers* son:

- **Errores de medición**: Errores en los procesos de recolección de datos o medición.
- **Errores de muestreo**: En algunos casos, los *outliers* pueden surgir debido a problemas en el proceso de muestreo.
- **Variabilidad natural**: La variabilidad inherente en ciertos fenómenos. Algunos sistemas pueden mostrar valores extremos debido a la naturaleza del proceso que se está estudiando.
- **Errores de entrada de datos**: Errores humanos durante la entrada de datos.
- **Errores experimentales**: En entornos experimentales, pueden ocurrir anomalías debido a factores no controlados, fallos en el equipo o eventos inesperados.
- **Muestreo de múltiples poblaciones**: Los datos se combinan inadvertidamente de múltiples poblaciones con características diferentes.
- **Outliers intencionales**: Los *outliers* se introducen intencionalmente para probar la robustez de los métodos estadísticos.

## <font color='8EC044'> **¿Porqué es importante gestionar los datos atípicos?** </font>

Los datos atípicos no son simpre el resultado de errores o de datos equivocados, es por ello que hablamos de gestionarlos dependiendo de cual es nuestro proposito de análisis y reconociendo las implicaciones que estos puedan tener en los resultados. Algunas de las razones que nos motivan a gestionar estos datos atípicos son:  

- **Impacto en el análisis estadístico**: Los datos atípicos influyen en las medidas estadísticas que son sensibles a valores extremos, como la media y la desviación estándar.
- **Asimetría y supuestos**: Los datos atípicos introducen asimetría en la distribución de los datos, violando los supuestos de normalidad de muchos modelos estadísticos, como la regresión lineal y las pruebas de hipótesis.
- **Rendimiento en el aprendizaje automático**: Los datos atípicos impactan los modelos predictivos, que a menudo otorgan una importancia desproporcionada a estos valores durante el entrenamiento, lo que disminuye la capacidad de generalización de los modelos.
- **Calidad de los datos**: Los datos atípicos pueden indicar problemas de calidad de los datos o errores causados por fallos en la medición, errores de entrada u otros problemas en la recopilación de datos.

## <font color='8EC044'> **Clasificaciones de los datos atípicos** </font>


Los datos atípicos se pueden clasificar en varias categorías según su naturaleza y contexto. Clasificarlos correctamente  permite tomar decisiones más informadas sobre si eliminarlos, tratarlos de manera especial o usarlos para análisis más profundos.

Algunas de las principales clasificaciones son:

### <font color='157699'> **Según su relación con el conjunto de datos** </font>
- **Outliers globales**: Son aquellos puntos de datos que se desvían significativamente del resto de todo el conjunto de datos. Son los más fáciles de identificar y tienden a ser muy extremos.
  - *Ejemplo*: Un valor de temperatura de 100°C en un conjunto de datos donde las temperaturas promedio oscilan entre 20°C y 30°C.
  
- **Outliers contextuales**: Estos *outliers* solo se consideran anómalos en función del contexto o entorno en el que se encuentran. Este tipo de *outlier* es más difícil de detectar porque depende de información adicional, como el tiempo o la localización.
  - *Ejemplo*: Un aumento inusual en las ventas de paraguas durante una tormenta fuerte no sería considerado un *outlier* en ese contexto, pero sí lo sería si ocurriera en una temporada seca.

- **Outliers colectivos**: Se refieren a grupos de puntos de datos que, en conjunto, se desvían del patrón general. Aunque los puntos individuales pueden no parecer *outliers*, el grupo en su conjunto sí lo es.
  - *Ejemplo*: Un grupo de usuarios que realiza una cantidad inusualmente alta de compras en un periodo corto de tiempo, lo que podría indicar comportamiento fraudulento.



### <font color='157699'> **Según su origen o causa** </font>

- **Outliers verdaderos**: Son valores que representan observaciones reales de eventos o fenómenos poco comunes pero legítimos.
  - *Ejemplo*: El tiempo de duración de un viaje debido a un fallo mecánico del transporte.
  
- **Outliers espurios**: Son *outliers* causados por errores de medición, errores humanos en la entrada de datos, o problemas técnicos.
  - *Ejemplo*: Un error de entrada que registra la altura de una persona como 300 metros.


### <font color='157699'> **Según su duración en el tiempo** </font>

- **Outliers permanentes**: Son aquellos que persisten y afectan los datos a lo largo del tiempo. Podrían indicar un cambio estructural en el sistema.
  - *Ejemplo*: Un cambio sostenido en las ventas de un producto después de una estrategia de marketing exitosa.

- **Outliers transitorios**: Son eventos anómalos que ocurren por un corto período y luego los datos regresan a su comportamiento normal.
  - *Ejemplo*: Un aumento breve en el tráfico de una página web después de una mención en los medios.

### <font color='157699'> **Según el dominio de los datos** </font>


- **Outliers univariados**: Se identifican analizando una sola variable. Si un valor se desvía significativamente de los demás en esa variable, se considera un *outlier*.
  - *Ejemplo*: Un ingreso extremadamente alto en un análisis de salarios.

- **Outliers multivariados**: Ocurren cuando una combinación de múltiples variables da lugar a un comportamiento anómalo. A menudo no se detectan si se consideran las variables de forma individual.
  - *Ejemplo*: Un cliente que gasta más de lo normal en varios tipos de productos simultáneamente.

## <font color='8EC044'> **Los datos atípicos no siempre son peligrosos** </font>


Algunas veces tendemos a asumir que los datos atípicos son producto de errores y de mala calidad en los datos. Sin embargo, en algunas ocasiones estos datos proveen información de interes.

Considere por ejemplo el caso en elq ue el análisis esta encaminado a la detección de fraudes con tarjeta de crédito, el análisis de *outliers* se vuelve crucial, ya que, en este contexto, son precisamente dichos datos en los que estamos interesados.

Los fraudes suelen ser eventos raros y atípicos dentro del comportamiento normal de transacciones de los clientes, por lo que los *outliers* representan actividades potencialmente fraudulentas. Las transacciones fraudulentas tienden a diferir significativamente de las transacciones regulares, estos pueden reflejar grandes compras inesperadas, compras repetitivas en poco tiempo o compras en lugares inusuales.
  
No todos los *outliers* son fraudulentos, por lo que es necesario analizar el contexto. Por ejemplo, un cliente que viaja al extranjero puede generar transacciones inusuales pero legítimas. La detección contextual ayuda a separar fraudes de comportamientos normales pero atípicos.

# <font color='056938'> **Conjunto de datos de prueba** </font>

Usaremos como conjunto de datos para el analisis, La base de datos `taxis` de `Seaborn` que proporciona información sobre los viajes en taxi en Nueva York, incluyendo variables relevantes que permiten analizar diversos aspectos del servicio de taxi


Las variables consideradas en la base de datos son


* `pickup`: Fecha y hora en que comenzó el viaje en taxi.
* `dropoff`: Fecha y hora en que finalizó el viaje.
* `passengers`: Número de pasajeros en el taxi durante el viaje.
* `distance`: Distancia recorrida en el viaje, medida en millas o kilómetros.
* `fare`: Costo total del viaje antes de propinas y peajes.
* `tip`: Monto de la propina dejada por el pasajero al conductor.
* `tolls`: Costo de los peajes pagados durante el viaje.
* `total`: Costo total del viaje, incluyendo tarifa, propinas y peajes.
* `color`: Color del taxi utilizado para el viaje.
* `payment`: Método de pago utilizado por el pasajero para el viaje.
* `pickup_zone`: Zona geográfica donde se realizó la recogida.
* `dropoff_zone`: Zona geográfica donde se realizó la entrega.
* `pickup_borough`: Distrito de la ciudad donde comenzó el viaje.
* `dropoff_borough`: Distrito de la ciudad donde finalizó el viaje.

In [ ]:
# Importar libreria seaborn
import seaborn as sns

# Cargar datos
taxis = sns.load_dataset('taxis')
taxis.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

Adicionamos dos columnas:
* `n_services`: que representa el número de viajes del conductor durante el último año
* `travel_time`: tiempo de viaje

In [ ]:
import numpy as np

# number of services
random_values = list(np.random.randint(0, len(taxis), round(0.02*len(taxis))))
services = [3*np.random.normal(150, 20) if i in random_values  else np.random.normal(150, 20) for i in range(len(taxis))]
taxis['n_services'] = services

# travel time
taxis['travel_time'] = taxis['dropoff'] - taxis['pickup']
taxis['travel_time'] = round(taxis['travel_time'].dt.total_seconds() / 60, 2)
taxis['travel_time'].describe()
taxis.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,n_services,travel_time
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,124.157033,6.25
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,145.065135,7.08
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,160.022243,7.40
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,127.328748,25.87
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,182.113646,9.53

# <font color='056938'> **Detección de datos atípicos** </font>


La detección de *outliers*, también conocida como detección de anomalías es el proceso de identificar puntos de datos que tienen valores extremos en comparación con el resto de la distribución. Las tecnicas para llevarlo a cabo son diversas y usualmente se usan de forma combinada. Es decir, se usan distintas técnicas en paralelo para confirmar la clsificación de los datos como atípicos

## <font color='8EC044'> **Estrategias basadas en visualización** </font>

Un primera estrategia de análisis para la identificación de datos atípicos es a través de la visualización de los datos.  En este caso discutiremos tres tipos de visualizaciones que son de utilidad:
* Histogramas
* Diagramas de caja y bigote (boxplots)
* Diagramas de dispersión

### <font color='157699'> **Histrogramas** </font>

Un histograma es una representación gráfica de la distribución de un conjunto de datos. Muestra la frecuencia de observaciones en intervalos distintos (o *bins*) de datos. Los histogramas pueden ayudar a descubrir posibles valores atípicos al estudiar la forma y dispersión de la distribución.

El eje `x` de un histograma muestra el rango de valores de la característica, dividido en intervalos, mientras que el eje y muestra la frecuencia de observaciones en cada intervalo. Los valores atípicos pueden identificarse como barras solitarias en los extremos del histograma.

Generamos el histrograma del número de servicios `n_services` del conductor asociado a cada servicio

In [ ]:
import plotly.express as px

variable = 'n_services'
n_bins = 100

fig = px.histogram(taxis[variable], nbins=n_bins, title=f'Histograma de {variable}')

# Show the plot
fig.show()

Note que los datos parecen estar distribuidos normalmente alrededor de 150 viajes. Sin embargo, se evidencia la presencia de datos atípicos con observaciones en las que el número de viajes es considerablemente mayor

#### <font color='46B8A9'> **Ejercicio** </font>

Analice mediante un histograma de la presencia de datos atípicos en la duración de los viajes

In [ ]:
# Escriba aqui su respuesta

### <font color='157699'> **Diagramas de caja** </font>

Un diagrama de caja, o *boxplot*, es una representación gráfica de la distribución de un conjunto de datos. Muestra al mismo tiempo la mediana, los cuartiles y el rango de los datos. Un *boxplot* es especialmente útil para identificar valores atípicos.

En un *boxplot*:
- La caja representa el rango intercuartílico (**IQR**), que es el rango entre el primer cuartil (percentil 25) y el tercer cuartil (percentil 75) de los datos.
- La línea dentro de la caja representa la mediana (percentil 50) de los datos.
- Los "bigotes" del gráfico se extienden desde la parte superior e inferior de la caja hasta los valores mínimos y máximos que estén dentro de 1.5 veces el **IQR** desde el primer y tercer cuartil.

Cualquier punto de datos fuera de los bigotes puede considerarse un valor atípico potencial y se representa como puntos individuales.


<img src="https://docs.google.com/uc?export=download&id=1PipNHQbT3zkSl28yYAwhDt8f2FHQpzHN" alt="picture" width="100%">

Generemos el diagrama de caja para la variable del tiempo de viaje`travel_time`

In [ ]:
import plotly.express as px

variable = 'travel_time'

# Create boxplot
fig = px.box(taxis,  y=variable, title=f'Boxplot de {variable}')
fig.show()

Note que en algunos casos puede ser de utilidad explorar si el comportamiento esta asociado al contexto o variables adicionales del conjunto de de datos.

In [ ]:
import plotly.express as px

variable = 'travel_time'

# Create boxplot
fig = px.box(taxis,  x='color', y=variable, title=f'Boxplot de {variable}')
fig.show()

### <font color='157699'> **Gráficos de dispersión** </font>

Un diagrama de dispersión (*scatter plot*) es otro tipo de gráfico utilizado para identificar valores atípicos en un conjunto de datos. Este gráfico representa visualmente los valores de un conjunto de datos a través de dos variables. Cada punto de datos se representa en el gráfico como un punto distinto, generando una colección de puntos que ayuda a identificar patrones y relaciones.

Podemos identificar rápidamente los valores atípicos al inspeccionar un diagrama de dispersión. Los valores atípicos son puntos que están inusualmente alejados de la mayoría, y su ubicación distintiva permite una identificación fácil.

In [ ]:
import plotly.express as px

variable_1 = 'travel_time'
variable_2 = 'distance'

fig = px.scatter(taxis, x=variable_1, y=variable_2,  title=f'Scatter Plot {variable_1} vs {variable_2}')

# Show the plot
fig.show()

Alternativamente podriamos crear el panel de todos los pares de gráficos

In [ ]:
import plotly.express as px


# Create a pair matrix plot (pair plot)
fig = px.scatter_matrix(
    taxis,
    dimensions=['passengers', 'distance', 'fare', 'tip', 'tolls', 'total', 'n_services', 'travel_time'],
    title="Pair Matrix Plot"
)

fig

#### <font color='46B8A9'> **Ejercicio** </font>

Qué podriamos inferir con base en el gráfico anterior

## <font color='8EC044'> **Estadisticas descriptivas** </font>

Algunas estadisticas descriptivas son una estrategia adicional para identificar la presencia de datos atípicos en el conjunto de datos y en algunos casos para identificar los valores puntales. Usaremos la función describe para construir algunas de las estadtsticas descriptivas del conjunto de datos

In [ ]:
taxis[['passengers', 'distance', 'fare', 'tip', 'tolls', 'total']].describe()

Respecto a la columna `total`, el resultado obtenido muestra una diferencia apreciable entre los valores mínimo y máximo. Además, con el percentil `75` se observa que el `75%` de los costos totales tienen valores por debajo de `20.3`, un valor alejado del máximo `174.82`. Similarmente, el dato máximo se encuentra considerablemente alejado en términos de el número de desviaciones estandar respecto a la media.

### <font color='46B8A9'> **Ejercicio** </font>

con base en las medidas de tendecia central y dispersión analice la presencia de datos atípicos la columna que considera el tiempo total del trayecto `travel_time`

In [ ]:
# Escriba aquí su respuesta

Los diferentes estadísticos descriptivos se ven afectados de forma diferente ante la presencia de datos atípicos.

### <font color='157699'> **Medidas de tendencia central** </font>

* **Media**: Siempre se ve afectada por un *outlier*, ya que considera la suma total de los valores de las observaciones

 >Si un *outlier* tiene un valor positivo mucho mayor que los otros valores, hará que la suma sea lo suficientemente grande como para que la media también sea mayor. Si el *outlier* tiene un valor muy pequeño, la media será un poco más baja.

* **Mediana**: La mediana se define como el valor medio en una distribución particular. Es el punto de datos en el cual la mitad de las observaciones están por encima y la otra mitad por debajo. **No se ve afectada por los *outliers***, por lo que la mediana se prefiere como medida de tendencia central cuando una distribución tiene observaciones extremas.

* **Moda**: La moda es el valor que aparece con mayor frecuencia en un conjunto de datos. Aunque la moda no se ve afectada directamente por los *outliers*, su presencia puede cambiar la moda de los datos si los *outliers* tienen un valor que se repite más que otros valores

### <font color='157699'> **Medidas de dispersión** </font>

* **Desviación estándar (DE)**: Se calcula usando todas las observaciones del conjunto de datos. Es una medida sensible porque se verá influenciada por los *outliers*, ya que la desviación estándar se calcula tomando la diferencia de cada caso con respecto a la media.

* **Desviación absoluta mediana (DAM)** Es una medida de dispersión que indica la variabilidad de un conjunto de datos. Se calcula como la mediana de las desviaciones absolutas de cada valor respecto a la mediana del conjunto de datos. Esta medida es robusta y menos sensible a valores atípicos en comparación con la desviación estándar.

  $\text{DAM} = \text{mediana}(|x_i - \text{mediana}(X)|)$

  Donde:
  * $x_i$ representa cada valor en el conjunto de datos.
  * $\text{mediana}(X)$ es la mediana del conjunto de datos.



* **Rango intercuartílico (IQR)**: El IQR es la diferencia entre el percentil 75 y el percentil 25. El IQR es más resistente a los *outliers*. Por definición, solo cubre el 50% central de los datos, por lo que los *outliers* están muy por fuera de este rango y la presencia de un pequeño número de *outliers* probablemente no cambiará significativamente esta medida. Esto es especialmente cierto en conjuntos de datos grandes.

* **Rango**: Es la medida más afectada por los *outliers*, ya que es la diferencia entre el valor máximo y el mínimo presente en el conjunto de datos.

# <font color='056938'> **Identificación de datos atípicos** </font>

Hemos descrito técnicas que nos permiten identificar la presencia de datos atípicos en el conjunto de datos. Sin embargo, en la mayoria de las ocasiones requerimos de la identificación particular de los registros y/o datos especificos que son atípicos. Si bien, en conjuntos reducidos de datos podriamos intentar hacerlo ayuddos por las técnicas descritas, por lo general haremos uso del calculo de algunos indicadores para cada regstro con el fin de evaluar si se trata o no de un dato atípico

## <font color='8EC044'> ***Z-score*** </font>


El *z-score* es una medida estadística que describe la posición de un valor en relación con la media de un conjunto de datos, expresada en términos de desviaciones estándar.  Este se calcula como: El z-score se calcula con la siguiente fórmula:


$z = \frac{(x - \mu)}{\sigma}$


Donde:
- $x$ es el valor que se está evaluando.
- $\mu$ es la media del conjunto de datos.
- $\sigma$ es la desviación estándar del conjunto de datos.

Un *z-score* alto indica que el valor se encuentra a una gran distancia de la media en comparación con otros valores en el conjunto de datos. Esto sugiere que podría ser un valor atípico.

Una regla emprica para considerar un valor alto del *z_score* es que este sea mayor que 3 veces o menor que menos 3 veces la desviación estandar, basado en el hecho de que para una distribución normal más del $99\%$ de las observaciones estan en el intervalo $[\mu-3\sigma, \mu+3\sigma]$. Análsis mas conservadores asumen un factor de $3.5$ o $4$ veces la desviación estandar

Esta estrategia sólo se usa en el caso de que los datos tengan una distribución normal.

Identifiquemos los datos atípicos para la variable del número de viajes `n_services` con base en el indicador `z_score`.

In [ ]:
# Import libraries
import numpy as np
from scipy.stats import zscore

# calculate z_core and it absolute value
z_scores = zscore(taxis['n_services'])
abs_z_scores = np.abs(z_scores)

# Select outliers with a factor of 3.5 times sigma
outliers_zscore1 = taxis[abs_z_scores > 3.5]


outliers_zscore1

## <font color='8EC044'> ***Z-score* modificado** </font>

El *z-score modificado* (también conocido como *z-score robusto*) es una variante del *z-score* tradicional que se utiliza para identificar valores atípicos en conjuntos de datos que pueden tener una distribución no normal o asimetrica (con sesgo a la derecha o a la izquierda), lo cual puede detectarse en el histograma o boxplot. Esta modificación utiliza la mediana y la desviación absoluta mediana (DAM) en lugar de la media y la desviación estándar.

$z = \frac{(x - \text{mediana}(X))}{1.4826*\text{MAD}  }$

Donde:
* $x$ es el valor que se está evaluando.
* $\text{mediana}(X)$ es la mediana del conjunto de datos.
* $\text{MAD}$ es la desviación absoluta mediana, que se calcula como la mediana de las desviaciones absolutas de cada valor respecto a la mediana.

El factor $1.4826$ se utiliza para hacer que la **MAD** sea consistentemente equivalente a la desviación estándar en una distribución normal. Esto permite que el z-score modificado sea comparable a los z-scores tradicionales. Empricaente se usa que los valores que se encuentren por debajo de -3.5 o por encima de 3.5 sean considerados atípicos

Identifiquemos los datos atípicos para la variable del tiempo de viaje `travel_time` con base en el indicador `z_score modificado`.

In [ ]:
# Importar librerias
import numpy as np
from scipy.stats import median_abs_deviation

# Obtener el valor MAD
mad_score = median_abs_deviation(taxis['travel_time'])
mediana = taxis['travel_time'].median()
zscore_mad = np.abs((taxis['travel_time']-mediana)/(1.4826*mad_score))
zscore_mad
# Obtener outliers
outliers_zscore_mad = taxis[zscore_mad > 5]
outliers_zscore_mad

## <font color='8EC044'> **Rango intercuartlico** </font>

El rango intercuartílico ($RIC$) es una medida de dispersión que indica la distancia entre el primer cuartil ($Q1$) y el tercer cuartil ($Q3$) de una distribución. Puede utilizarse para identificar outliers al ayudar a definir los límites a partir de los cuales los valores se consideran atípicos. Estos límites se calculan de la siguiente manera:

> $l_{inf} = Q1-(k * RIC)$

> $l_{sup} =  Q1 + (k * RIC)$

Donde  $k$ se puede reemplazar por 1.5 (outlier) o por 3 (outlier extremo). Los valores que se encuentren por debajo del límite inferior o por encima del límite superior se consideran outliers.

Identifiquemos los datos atípicos para la variable del tiempo de viaje `travel_time` con base en el indicador del rango intrcuartílico `RIQ`.

In [ ]:
# Calcular cuartiles a partir de la función percentil
Q3 = taxis['total'].quantile(0.75) # Tercer cuartil = Percentil 75
Q1 = taxis['total'].quantile(0.25) # Primer cuartil + Percentil 25

# Obtener RIC
ric = Q3 - Q1

# Definir limite inferior y superior
superior = Q3 + (3 * ric)
inferior = Q1 - (3* ric)

# Identificar outliers
outliers_RIC = taxis[(taxis['total'] < inferior) | (taxis['total'] > superior)]
outliers_RIC

# <font color='056938'> **Tratamiento de datos atípicos** </font>

No existe una única técnica apropiada para todos los casos respecto a como tratar los datos atípicos. La estrategia sleccionada para manejar estos valores dependera del contexto y la naturaleza del análisis. Algunas de las estrategias más usadas son:


* Eliminar los datos atípicos
* Mantener los datos atípicos
* Realizar transformaciones
* Acotar los valores de los datos átipocos
* Imputar los datos atípicos

## <font color='8EC044'> **Eliminar los datos atípicos** </font>

Eliminar los datos atípicos siempre es una medida drástica y debe tomarse solo en condiciones extremas. Por ejemplo, cuando estamos muy seguros de que el dato atípico se debe a un error de medición, lo cual generalmente no sabemos mientras hacemos el análisis.

Al eliminarlos es importante considerar la pérdida de información. Es decir, cuando tienes una gran cantidad de datos y  eliminar un dato atípico dudoso no afectará significativamente a tu muestra.

### <font color='46B8A9'> **Ejercicio** </font>

Considere el dataframe `taxis`, cual sería la perdida de información, es decir el porcentaje del número total de registros si decidimos eliminar todos los datos atípicos en cualquiera de las variables `[n_services, travel_time, total]`

In [ ]:
# Ingrese aquí su respuesta

## <font color='8EC044'> **Mantener datos atípicos** </font>

Habrá ocasiones en las que no haya razones suficientes para eliminar los datos atípicos, por ejemplo en el caso en el que dichos datos brindan información importante para el análisis.

En estos casos será posible mantener los datos atípicos pero deberemos acudir a estrategías que nos permitan reducir su impacto negativo en los resultados. Por ejemplo, podríamos:

* **Transformar los datos**: Aplicar transformaciones matemáticas (como logaritmos, raíz cuadrada o escalado) puede reducir la influencia de los datos atípicos.
>Por ejemplo, en distribuciones asimétricas, una transformación logarítmica puede reducir la distancia entre los valores atípicos y el resto de los datos.

* **Modelos robustos**: Favorecer el uso de técnicas de modelado  más robustas a los outliers. Por ejemplo:
  >  *Regresión robusta* (p. ej., la regresión de mínimos cuadrados ponderados) que minimiza el impacto de los datos atípicos en los resultados del modelo.

 >*Modelos de árboles* como los árboles de decisión o Random Forest son menos sensibles a los outliers en comparación con modelos lineales.

## <font color='8EC044'> **Acotar el valor de los datos atípicos** </font>

En esta técnica, también conocida como *winzorizing* esencialmente establecemos un límite para los valores atípicos mínimos y máximos. Cualquier valor por encima o por debajo del límite se ajusta al valor máximo o mínimo respectivamente.

> Por ejemplo, si establecemos un límite máximo de 20 para una variable, cualquier valor atípico por encima de 20 se ajustará a 20. Esta técnica se utiliza cuando se puede asumir que todos los valores atípicos expresan los mismos comportamientos o patrones.

Para limitar los valores atípicos, se calcula un límite superior y un límite inferior. El calculo de este límite dependerá de aspectos como el contexto y el tipo de distribuición de los datos.

## <font color='157699'> **Acotar a un valor límite natural** </font>

En algunos casos se conoce o puede establecerse un valor límite natural para los datos. Por ejemplo:
  > Los tiempos y distancias recorradias no pueden ser menores que cero, por lo tanto todos los valores menores que cero se acotaran a este valor

  > La evaluación de un estudiante no puede ser superior a 5, así que todos los valores superiores se acotarán a este valor.

  > En una encuesta de ingresos estamos interesados solo en población de ingresos medios, por lo que los valores muy altos de ingresos se acotaran a un límite superior


## <font color='157699'> **Acotar con cuantiles** </font>


Una de las formas más comunes es definir un rango de percentiles (por ejemplo, el 5% y el 95%) y sustituir los valores que se encuentran por debajo o por encima de esos percentiles por los valores correspondientes al límite del percentil. Esto puede hacerse de varias maneras:
   - **Unilateral**: Solo se limita el lado superior o inferior de la distribución.
   - **Bilateral**: Se limitan ambos extremos, inferior y superior.

## <font color='157699'> **Acotar utilizando el rango intercuartílico (IQR)** </font>

Una técnica común es utilizar $1.5$ veces el $IQR$ para definir los límites. Los valores más allá de estos límites se sustituyen por los valores límite calculados. En principio podria asumirse como un caso particular de la acotación por cuantiles

## <font color='157699'> **Acotar usando desviaciones estándar** </font>

En esta variante, los límites superior e inferior se establecen en función de un número determinado de desviaciones estándar desde la media. Por ejemplo, se puede establecer un límite de $±3$ desviaciones estándar. Cualquier valor que exceda este rango se reemplaza por los valores límites. Es particularmente adecuado cuando se asume que los datos siguen una distribución aproximadamente normal.

Aunque estas operaciones pueden hacerse manualmente, es posible hacerlas a través de librerias como `feature_engine`

In [ ]:
!pip install feature_engine

In [ ]:
import pandas as pd
from feature_engine.outliers import Winsorizer

# Example DataFrame
df = taxis[['n_services']].copy()

# Using quantiles for capping
winsor_quantiles = Winsorizer(capping_method='quantiles', tail='both', fold=0.05)
df['n_services_capped_quantiles'] = winsor_quantiles.fit_transform(df[['n_services']])

# Using standard deviations for capping
winsor_std = Winsorizer(capping_method='gaussian', tail='both', fold=3)  # 3 standard deviations
df['n_services_capped_std'] = winsor_std.fit_transform(df[['n_services']])

# Using IQR for capping
winsor_iqr = Winsorizer(capping_method='iqr', tail='both')
df['n_services_capped_iqr'] = winsor_iqr.fit_transform(df[['n_services']])

df

In [ ]:
# Import libraries
import numpy as np
from scipy.stats import zscore

# calculate z_core and it absolute value
z_scores = zscore(df['n_services'])
abs_z_scores = np.abs(z_scores)

# Select outliers with a factor of 3.5 times sigma
outliers_zscore1 = df[abs_z_scores > 3.5]
outliers_zscore1.head()

Evidenciemos el comportamiento de lso datos antes y despues de acotar su valor

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np


# Create a subplot figure
fig = make_subplots(rows=1, cols=2, subplot_titles=( 'Sin acotar', 'Acotado dist. normal',))


fig.add_trace(go.Histogram(x=df['n_services']) , row=1, col=1)
fig.add_trace(go.Histogram(x=df['n_services_capped_std']) , row=1, col=2)



# Update layout for better readability
fig.update_layout(title_text="Acotamiento (winzoring)", showlegend=False)

# Show the plot
fig.show()

## <font color='8EC044'> **Imputar valores** </font>

Una última técnica posible, es asumir los valores atípicos como datos faltantes y usar alguna de las técnicas de imputación de valores que discutimos en la clase anterior

# <font color='056938'> **Reto** </font>

Considere el conjunto de datos del sistema ecoBici para efectuar el análisis de datos atípicos. Use la siguiente [plantilla](https://drive.google.com/file/d/1UnTgeZZbo-5LKCe1H6uCE4GyS33oPxV4/view?usp=sharing)